DD-DeCaF/simulations

- model/app.py
- tests/test_end_to_end.py
group models per species, and add function to get which models are
possible per species
> feat: support multiple models per organism

- model/app.py
- tests/test_end_to_end.py
> Revert "feat: support multiple models per organism"

- model/adapter.py
- model/app.py
- tests/test_end_to_end.py
- tests/test_integration.py
- tests/test_unit.py
Model boundary adjustments should be based on a list of values from
which we compute an upper and a lower bound.
> feat: handle multiple measurements

- model/adapter.py
- tests/test_unit.py
Measurements can include missing values.
> feat: support missing values in measurements

- model/app.py
> fix: ppp points can be numpy float

- model/adapter.py
- model/app.py
- requirements.txt
- tests/test_unit.py
- adjust for changes upstream (use of Series)
- adjust some minor idiosyncracies on naming of boundary reactions
> refactor: upgrade to cobra06

- .gitignore
- .travis.yml
- Dockerfile
- docker-compose.yml
- model/adapter.py
- model/app.py
- requirements.txt
- tests/test_end_to_end.py
- tests/test_unit.py
@warlink you can use this branch for testing, the pr should be updated after cameo/pandas issue resolved
> wip: Fix/pkg updates

- model/adapter.py
Taking the insider information about gnomic strings into account
Query only the KEGG identifiers with the id mapper
The PR https://github.com/DD-DeCaF/model/pull/28 should be merged after this one
> fix: model adapter

- model/app.py
- requirements.txt
Move the pfba-fva to cobra to sort bug where an added constraint
couldn't be removed twice.
To be adjusted once https://github.com/opencobra/cobrapy/pull/535 has been merged.
> fix: broken mixing cameo and cobra for pfba/fva

- model/adapter.py
- model/app.py
Sort identifiers in reaction equations to db_name's based on matching
them to regular expressions.
> fix: support reaction equation with non-kegg id

- model/adapter.py
- tests/test_unit.py
Gene identifiers are somewhat more explicit way of indicating what
should be knocked so support this.
> feat: support knocking genes by id

- model/app.py
- requirements.txt
- tests/test_end_to_end.py
- tests/test_integration.py
- tests/test_unit.py
Quick temporal hack until the function in cobrapy is not implemented
> refactor: use metabolites dictionary, not reaction string

- model/adapter.py
- tests/unit/test_storage.py
[Related PR in iloop-to-model](https://github.com/DD-DeCaF/iloop-to-model/pull/43)
> Constrict growth rate pseudoreaction if measurement is provided

- src/model/exceptions.py
- src/model/resources.py
- src/model/storage.py
- tests/unit/test_storage.py
Implements handling of permission errors returned from model-storage
> Handle insufficient permissions

- src/model/resources.py
This endpoint returns a model modified with the given operations, but
as far as I can tell we have no use case for this.
> Remove unused endpoint

- src/simulations/modeling/adapter.py
- Ensure the compartment id is set on new metabolites
- Instead of creating an intracellular demand reaction, create the extracellular metabolite + transport and exchange reactions as the later logic of applying metabolomics assumes the exchange reaction always exists
Based this on the `fix-genotype` branch to deal with the merge conflicts in advance.
> Fix compartments for added metabolites

- src/simulations/modeling/adapter.py
* Clean up function in general.
My apologies for wrapping too many changes into a single commit.
> refactor: compare lower case gene names

- src/simulations/exceptions.py
- src/simulations/modeling/adapter.py
- src/simulations/modeling/cobra_helpers.py
- src/simulations/modeling/operations.py
Ref https://github.com/DD-DeCaF/simulations/pull/136/files/77c153d2e3fbb7dfc861b705165b267c1167c420#diff-ca5d6ca25a525e067199a8279055a458
> Abstract parsing bigg metabolite identifier to a function

- src/simulations/exceptions.py
- src/simulations/modeling/adapter.py
- src/simulations/modeling/cobra_helpers.py
Fixes https://sentry.io/organizations/nnf-cfb-cad/issues/1133407425/?project=257463&referrer=slack
> fix: store compartment id on exception instance

- src/simulations/modeling/adapter.py
- src/simulations/modeling/cobra_helpers.py
Ref https://github.com/DD-DeCaF/simulations/pull/148#discussion_r355944887
> refactor: implement exchange reaction logic as cobra helper function
